public_catalog: 'https://catalog-preview.appstwo.tadl.org'
format_options: [['All Formats', 'fmt', 'all'], ['Books', 'fmt', 'a'], ['Books - Fiction', 'fmt', 'a', true ], ['Books - Non-fiction', 'fmt', 'a', false], ['Large Print', 'call_prefix', 'LP'], ['Large Print - Fiction', 'call_prefix', 'LP', true], ['Large Print - Non-fiction', 'call_prefix', 'LP', false], ['Audiobooks', 'shelving_location', '515,518,546,571,572,582,584,590,597,680'], ['Audiobooks - Fiction', 'shelving_location', '515,518,546,571,572,582,584,590,597,680', true], ['Audiobooks - Non-fiction', 'shelving_location', '515,518,546,571,572,582,584,590,597,680', false], ['eBooks', 'electronic', 'ebooks'], ['eBooks - Fiction', 'electronic', 'ebooks', true], ['eBooks - Non-fiction', 'electronic', 'ebooks', false], ['Movies / TV', 'fmt', 'g'], ['Music', 'fmt', 'j'], ['Video Games', 'shelving_location', '777']]
format_electronic: [['ebooks', ['Safari', 'OverDrive', 'Hoopla'], ['text', 'kit', 'sound recording-nonmusical', 'cartographic', 'software, multimedia']]]
lists:
  - group: "Books"
    searches:
      - name: "tadlnewfiction"
        display_name: "New Fiction"
        params: {query: "619", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=619&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"
      - name: "tadlnewnonfiction"
        display_name: "New Non-fiction"
        params: {query: "621", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=621&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"
  - group: 'Video'
    searches:
      - name: "tadlhotdvds"
        display_name: "HOT DVDs"
        params: {query: "682", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=682&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"
      - name: "tadlnewdvds"
        display_name: "New DVDs"
        params: {query: "687", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=687&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"
      - name: "tadltcfilmfest"
        display_name: "TC Film Festival"
        params: {query: "778", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=778&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"
  - group: 'Music'
    searches:
      - name: "tadlnewmusic"
        display_name: "New Music"
        params: {query: "686", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=686&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"
      - name: "tadlhottunes"
        display_name: "HOT Tunes"
        params: {query: "684", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
        search_link: "/search?query=684&type=shelving_location&fmt=all&sort=pubdateDESC&location=22"

