format_options: [['All Formats', 'fmt', 'all'], ['Books', 'fmt', 'a'], ['Large Print', 'call_prefix', 'LP'], ['Audiobooks', 'shelving_location', '515,518,546,571,572,582,584,590,597,680'], ['eBooks', 'electronic', 'ebooks'], ['Movies / TV', 'fmt', 'g'], ['Music', 'fmt', 'j'], ['Video Games', 'shelving_location', '777']]
format_electronic: [['ebooks', ['Safari', 'OverDrive', 'Hoopla'], ['text', 'kit', 'sound recording-nonmusical', 'cartographic', 'software, multimedia']]]
lists:
  - name: 'tadlwoodnewbooks'
    prettyname: 'New Books'
    params: {query: "", type: "keyword", fmt: "Books", sort: "pubdateDESC", location: "22"}
  - name: 'tadlwoodnewvideo'
    prettyname: "New Video"
    params: {query: "", type: "keyword", fmt: "Movies / TV", sort: "pubdateDESC", location: "22"}
  - name: 'tadlwoodnewmusic'
    prettyname: 'New Music'
    params: {query: "", type: "keyword", fmt: "Music", sort: "pubdateDESC", location: "22"}
