format_options: [['All Formats', 'fmt', 'all'], ['Books', 'fmt', 'a'], ['Large Print', 'call_prefix', 'LP'], ['Audiobooks', 'shelving_location', '515,518,546,571,572,582,584,590,597,680'], ['eBooks', 'electronic', 'ebooks'], ['Movies / TV', 'fmt', 'g'], ['Music', 'fmt', 'j'], ['Video Games', 'shelving_location', '777']]
format_electronic: [['ebooks', ['Safari', 'OverDrive', 'Hoopla'], ['text', 'kit', 'sound recording-nonmusical', 'cartographic', 'software, multimedia']]]
lists:
  - group: "tadl_one"
    searches:
      - name: "tadlnewbooks"
        display_name: 'New Fiction and Non-fiction'
        params: {query: "619,621", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadlnewfiction"
        display_name: "New Fiction"
        params: {query: "619", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadlnewnonfiction"
        display_name: "New Non-fiction"
        params: {query: "621", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
  - group: 'tadl_two'
    searches:
      - name: "tadlnewvideo"
        display_name: "New Movies and TV"
        params: {query: "687,682", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadlhotdvds"
        display_name: "HOT DVDs"
        params: {query: "682", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadlnewdvds"
        display_name: "New DVDs"
        params: {query: "687", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadltcfilmfest"
        display_name: "TC Film Festival"
        params: {query: "778", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
  - group: 'tadl_three'
    searches:
      - name: "tadlnewandhotmusic"
        display_name: 'New and HOT Music'
        params: {query: "686,684", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadlnewmusic"
        display_name: "New Music"
        params: {query: "686", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}
      - name: "tadlhottunes"
        display_name: "HOT Tunes"
        params: {query: "684", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "22"}

