public_catalog: 'https://kclmobile.apps.tadl.org'
format_options: [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_electronic: [['ebooks', ['Safari', 'OverDrive', 'Hoopla'], ['text', 'kit', 'sound recording-nonmusical', 'cartographic', 'software, multimedia']]]
lists:
  - group: "Books"
    searches:
      - name: "sbbdl_new_fiction"
        display_name: "New Fiction"
        params: {query: "1011", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "46"}
        search_link: "/search?query=1011&type=shelving_location&fmt=all&sort=pubdateDESC&location=46"
      - name: "sbbdl_new_non-fiction"
        display_name: "New Non-fiction"
        params: {query: "1012", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "46"}
        search_link: "/search?query=1012&type=shelving_location&fmt=all&sort=pubdateDESC&location=46"

  - group: 'Video'
    searches:
      - name: "sbbdl_new_movies"
        display_name: "New Movies"
        params: {query: "1020", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "46"}
        search_link: "/search?query=1020&type=shelving_location&fmt=all&sort=pubdateDESC&location=46"

