public_catalog: 'https://kclmobile.apps.tadl.org'
format_options: [['All Formats', 'fmt' ,'all'], ['Books', 'fmt' ,'a'],['Movies / TV', 'fmt' ,'g']]
format_electronic: [['ebooks', ['Safari', 'OverDrive', 'Hoopla'], ['text', 'kit', 'sound recording-nonmusical', 'cartographic', 'software, multimedia']]]
lists:
  - group: "Books"
    searches:
      - name: "kcl_new_fiction"
        display_name: "New Books"
        params: {query: "1032", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "44"}
        search_link: "/search?query=1032&type=shelving_location&fmt=all&sort=pubdateDESC&location=44"

  - group: 'Video'
    searches:
      - name: "kcl_new_video"
        display_name: "New Video"
        params: {query: "951", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "44"}
        search_link: "/search?query=951&type=shelving_location&fmt=all&sort=pubdateDESC&location=44"

