public_catalog: 'https://catalog-preview.appstwo.tadl.org'
format_options: [['All Formats', 'fmt', 'all'], ['Books', 'fmt', 'a'], ['Books - Fiction', 'fmt', 'a', true ], ['Books - Non-fiction', 'fmt', 'a', false], ['Large Print', 'call_prefix', 'LP'], ['Large Print - Fiction', 'call_prefix', 'LP', true], ['Large Print - Non-fiction', 'call_prefix', 'LP', false], ['Audiobooks', 'shelving_location', '515,518,546,571,572,582,584,590,597,680'], ['Audiobooks - Fiction', 'shelving_location', '515,518,546,571,572,582,584,590,597,680', true], ['Audiobooks - Non-fiction', 'shelving_location', '515,518,546,571,572,582,584,590,597,680', false], ['eBooks', 'electronic', 'ebooks'], ['eBooks - Fiction', 'electronic', 'ebooks', true], ['eBooks - Non-fiction', 'electronic', 'ebooks', false], ['Movies / TV', 'fmt', 'g'], ['Music', 'fmt', 'j'], ['Music - Vinyl','shelving_location','533'], ['Video Games', 'shelving_location', '777'], ['Things', 'shelving_location', '1006']]
format_electronic: [['ebooks', ['Safari', 'OverDrive', 'Hoopla'], ['text', 'kit', 'sound recording-nonmusical', 'cartographic', 'software, multimedia']]]
lists:
  - group: "Books"
    searches:
      - name: "sbbdl_new_fiction"
        display_name: "New Fiction"
        params: {query: "1011", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "46"}
        search_link: "/search?query=1011&type=shelving_location&fmt=all&sort=pubdateDESC&location=46"
      - name: "sbbdl_new_non-fiction"
        display_name: "New Non-fiction"
        params: {query: "1012", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "46"}
        search_link: "/search?query=1011&type=shelving_location&fmt=all&sort=pubdateDESC&location=46"

  - group: 'Video'
    searches:
      - name: "sbbdl_new_movies"
        display_name: "New Movies"
        params: {query: "1020", type: "shelving_location", fmt: "all", sort: "pubdateDESC", location: "46"}
        search_link: "/search?query=1011&type=shelving_location&fmt=all&sort=pubdateDESC&location=46"

