system_name: "Kalkaska County Library"
catalog_name: "Kalkaska County Library Online Catalog"
cover_url_prefix_lg: "https://catalog.tadl.org/opac/extras/ac/jacket/large/r/"
cover_url_prefix_md: "https://catalog.tadl.org/opac/extras/ac/jacket/medium/r/"
cover_url_prefix_sm: "https://catalog.tadl.org/opac/extras/ac/jacket/small/r/"
default_layout: 'list'
evergreen_server: 'mr-v2a.catalog.tadl.org'
logo_icon: "tadl-icon.png"
location_options: [['All Locations','43','KCL-SYS', 'All Loctions'],['Kalkaska Main Branch', '44', 'KCL', 'Kalkaska'],['Coldsprings Branch', '56', 'KCL-COLD', 'Coldsprings'],['Garfield Township Branch', '57','KCL-GARF','Garfield']]
location_options_minus_all: [['Kalkaska Main Branch', '44', 'KCL', 'Kalkaska'],['Coldsprings Branch', '56', 'KCL-COLD', 'Coldsprings'],['Garfield Township Branch', '57','KCL-GARF','Garfield']]
view_default: 'list'
location_default: '43'
location_single: true
machine_readable: 'https://mr-v2a.catalog.tadl.org/'
melcat_enabled: true
melcat_link: 'https://elibrary.mel.org/search/a?searchtype=X&SORT=D&submit=Submit&searcharg='
melcat_id_display: false
primary_card_display: false
online_payment: false
online_registration: true
register_link: '/register'
register_link_show: true
register_link_text: 'Get a Library Card'
register_location: '44'
register_location_name: 'Kalkaska County Library'
register_agreement_text: 'kcl'
register_newsletter: false
forgot_password_text: 'Forgot/lost password?'
search_placeholder: 'Books, movies, music & more!'
account_info: true
system_lock:
  card_prefix_allow: '90247'
added_nav_links:
  - name: "Website"
    url: "https://www.kalkaskalibrary.org/"
summer_reading: false
summer_reading_registration: false
summer_reading_reporting: false
