system_name: "Traverse Area District Library"
catalog_name: "Traverse Area District Library Online Catalog"
cover_url_prefix_lg: "https://catalog.tadl.org/opac/extras/ac/jacket/large/r/"
cover_url_prefix_md: "https://catalog.tadl.org/opac/extras/ac/jacket/medium/r/"
cover_url_prefix_sm: "https://catalog.tadl.org/opac/extras/ac/jacket/small/r/"
default_layout: 'list'
evergreen_server: 'mr-v2.catalog.tadl.org'
logo_icon: "tadl-icon.png"
location_options: [['All Locations', '22', 'TADL-ALL', 'All locations'], ['Traverse City', '23', 'TADL-WOOD','Woodmere (Main) Branch'], ['Interlochen', '24', 'TADL-IPL','Interlochen Public Library'], ['Kingsley', '25', 'TADL-KBL','Kingsley Branch Library'], ['Peninsula', '26', 'TADL-PCL','Peninsula Community Library'], ['East Bay', '28', 'TADL-EBB','East Bay Branch Library'], ['Fife Lake', '27', 'TADL-FLPL','Fife Lake Public Library']]
location_options_minus_all: [['Traverse City', '23', 'TADL-WOOD','Woodmere (Main) Branch'], ['Interlochen', '24', 'TADL-IPL','Interlochen Public Library'], ['Kingsley', '25', 'TADL-KBL','Kingsley Branch Library'], ['Peninsula', '26', 'TADL-PCL','Peninsula Community Library'], ['East Bay', '28', 'TADL-EBB','East Bay Branch Library'], ['Fife Lake', '27', 'TADL-FLPL','Fife Lake Public Library']]
view_default: 'list'
location_default: '22'
location_single: false
machine_readable: 'https://mr-v2.catalog.tadl.org/'
melcat_enabled: true
melcat_link: 'https://elibrary.mel.org/search/a?searchtype=X&SORT=D&submit=Submit&searcharg='
melcat_id_display: true
primary_card_display: true
online_payment: true
online_payment_url: 'https://www.tadl.org/pay/pay.cgi'
online_payment_text: 'Pay fines online'
online_registration: true
register_link: '/register'
register_link_show: true
register_link_text: 'Get a Library Card'
register_location: '23'
register_location_name: 'any TADL location'
register_agreement_text: 'tadl'
register_newsletter: true
register_listapi_url: 'https://www.tadl.org/listapi/tadl/'
forgot_password_text: 'Forgot/lost password?'
search_placeholder: 'Books, movies, music & more!'
account_info: true
added_nav_links:
  - name: "Website"
    url: "https://www.tadl.org/"
summer_reading: true
<<<<<<< HEAD
summer_reading_registration: true
=======
summer_reading_registration: false
>>>>>>> d9351afefb8293d4c4adc582cecb1117a77818b2
summer_reading_reporting: true
