cover_url_prefix_lg: "https://catalog.tadl.org/opac/extras/ac/jacket/large/r/"
cover_url_prefix_md: "https://catalog.tadl.org/opac/extras/ac/jacket/medium/r/"
cover_url_prefix_sm: "https://catalog.tadl.org/opac/extras/ac/jacket/small/r/"
evergreen_server: 'mr-v2.catalog.tadl.org'
logo_icon: "tadl-icon.png"
location_options: [['Woodmere', '23', 'TADL-WOOD'], ['All Locations', '22', 'TADL-ALL'], ['Interlochen', '24', 'TADL-IPL'], ['Kingsley', '25', 'TADL-KBL'], ['Peninsula', '26', 'TADL-PCL'], ['East Bay', '28', 'TADL-EBB'], ['Fife Lake', '27', 'TADL-FLPL']]
location_options_minus_all: [['Woodmere', '23', 'TADL-WOOD'], ['Interlochen', '24', 'TADL-IPL'], ['Kingsley', '25', 'TADL-KBL'], ['Peninsula', '26', 'TADL-PCL'], ['East Bay', '28', 'TADL-EBB'], ['Fife Lake', '27', 'TADL-FLPL']]
view_default: 'list'
location_default: '22'
location_single: false
online_payment: true
online_payment_url: 'https://www.tadl.org/pay/pay.cgi'
online_registration: true
register_newsletter: true
register_form: '/register'
register_location: '23'
register_agreement_text: 'tadl'
register_link: true
register_link_text: 'Get a Library Card'
register_location_name: 'Traverse City Library'
register_listapi_url: 'https://www.tadl.org/listapi/tadl/'
forgot_password_text: 'Forgot/lost password?'
search_placeholder: 'Books, movies, music & more!'
added_nav_links:
  - name: "Website"
    url: "https://www.tadl.org/"
